Implement Firebase auth
Hack-Weekly/tangerine-moose-blog pull request #19
Opened 2023-04-04 03:39 UTC by JoeBouchard

I spent way too long barking up the wrong tree. After messing with a variety of packages, I ended up settling on the default firebase package. One restriction is I believe it can only be used on client side components, which might put a damper on optimizations.

2023-04-04 14:52 UTC, zwwuu requested changes

2023-04-04 14:52 UTC, zwwuu commented on app/page.js
maybe merge with https://github.com/Hack-Weekly/tangerine-moose-blog/pull/18 first, so the styling is correct

2023-04-04 14:52 UTC, zwwuu commented on components/signIn.js
will probably need to move this to a context hook like AuthContext. looks good for now.

2023-04-04 17:34 UTC, thebeatlesphan reviewed
I pulled your branch and am trying to get it connected to my Firebase but I'm getting errors every corner.
I think I found the new tutorial for NextJS13 that you followed for this.
https://www.freecodecamp.org/news/create-full-stack-app-with-nextjs13-and-firebase/

I was able to get the app connected to Firebase but I can't get the Auth to work.

I keep getting errors with Firebase not being initialized and my firebase_config missing / incorrect. I've tried hardcoding and using dotenv for my config. I have to do some weird stuff to make it through the errors.


March 4 5:43PM

![image](https://user-images.githubusercontent.com/59131637/229929518-36ba3958-98f8-4c95-8ed2-5a39f8c43c6b.png)

I got the auth working on the live db. There's something going on with my .env file.
I'm not sure why referencing it is not working. I npm install dotenv and created a .env file with proper syntax.
I was able to console.log the variables out and they match the SDK but the firebase.js won't take it. 
I had to hardcode my firebaseConfig in to make it work

2023-04-05 00:34 UTC, thebeatlesphan commented
I copied your branch and tried to resolve the deployment issue but was unsuccessful.

I think there's something going on with the deployment and firebase configs.
The deployment failed details just takes me to a 404 page.
Everything is looking fine code-wise.

2023-04-05 01:25 UTC, zwwuu commented
fixed in https://github.com/Hack-Weekly/tangerine-moose-blog/pull/24

2023-04-05 01:25 UTC, closed without merging