Andy
Hack-Weekly/tangerine-moose-blog pull request #3
Opened 2023-04-02 14:18 UTC by thebeatlesphan

2023-04-02 18:40 UTC, JoeBouchard commented on app/moose.ico
Nice! I like it!

2023-04-02 18:44 UTC, JoeBouchard requested changes
Overall, looks like a good place for us to start! I left one comment on DefaultTags to make it more optimized for NextJS.

2023-04-02 18:44 UTC, JoeBouchard commented on app/default-tags.js
Consider moving this into the "metadata" variable in layout.js. https://beta.nextjs.org/docs/upgrade-guide#step-3-migrating-nexthead. The data looks good!

2023-04-02 18:58 UTC, zwwuu commented on .gitignore
why do we need to include this favicon?

2023-04-02 22:48 UTC, thebeatlesphan commented on app/default-tags.js
I've actually referenced the moose favicon in that i've put in app/moose.ico.
The app doesn't seem to take it for some reason.
I was able to find the reference of the vercel icon in the .next folder and just replaced it and renamed it exactly the same and it worked locally,

After I committed changes, it seems to have reverted on its own.


**See bold below**
export default function DefaultTags() {
  return (
    <>
      <title>Tangerine Moose Blog App</title>
      <meta charset="utf-8" />
      <meta
        name="description"
        content="Blog app engineered by the Tangerine Moose team"
      />
      <meta author="Tangerine Moose Team" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      **<link rel="icon" href="/moose.ico" />**
    </>
  );
}

2023-04-02 22:49 UTC, thebeatlesphan commented on .gitignore
See comment below.
it replaces the vercel icon with the moose icon I randomly chose.
I just happen to rename it the same because of how default nextjs files reference the <link> icon.

2023-04-02 22:52 UTC, JoeBouchard commented on app/default-tags.js
I think moose.ico might need to be moved to the public folder for it to work.

2023-04-02 22:58 UTC, thebeatlesphan commented on app/default-tags.js
I moved it and its not taking. I'll share in the discord for you to test.

2023-04-03 01:09 UTC, zwwuu commented
merge this one instead https://github.com/Hack-Weekly/tangerine-moose-blog/pull/4

2023-04-03 01:09 UTC, closed without merging